### ISSUE TITLE
Could you please post a compiled version?

### ISSUE THREAD

**Issue by fornaciogiorgi** [BradlyLanducci/Korg-Minilogue-XD-FX#1]
Thank you!!!

**Comment by BradlyLanducci** [comment]
Which effect in particular? I could do all of them, but that might take me a few days or so as I need to finish a couple of them.

**Comment by fornaciogiorgi** [comment]
Thank you Brad for the quick reply. I was talking about **Multifx**.
Chorus, flanger, highpass filter, mono delay, pingpong and waveshaper have the .mnlgxdunit file, or maybe I was missing them this afternoon. :D
Now I can easily load them on an nts-1 (it will probably work).

**Comment by BradlyLanducci** [comment]
Ah yes, I never actually finished this, I likely won't be any time soon as I've moved onto some non Korg related projects. 

Honestly, none of these algorithms sound very good in my opinion and I would advise checking out the Korg Unit Index https://korginc.github.io/logue-sdk/unit-index/.

I expect that eventually I will come back to these once I have time to make them higher quality effects!

**Comment by fornaciogiorgi** [comment]
Thank you Bradly, just checking before moving to paid software (the bundles cost way too much in comparison to an NTS-1 unit, I am looking for someone willing to trade :D )

**Comment by BradlyLanducci** [comment]
Hello, just responding after finally getting around to updating these. The ntkdigunits should also work in minilogue-XD :)
